In [1]:
import torch

In [2]:
# Number
t1 = torch.tensor(9.)
t1

tensor(9.)

In [3]:
# vector
t2 = torch.tensor([1,2,3,4,5])
t2

tensor([1, 2, 3, 4, 5])

Matrix

In [4]:
t3 = torch.tensor([[2., 6], 
                   [8, 9], 
                   [9, 4]])

t3

tensor([[2., 6.],
        [8., 9.],
        [9., 4.]])

In [5]:
x = torch.Tensor(2, 3)  # An un-initialized Tensor object. x holds garbage data.
y = torch.rand(2, 3)    # Initialize with random values

z1 = x + y
z2 = torch.add(x, y)            

print("x")
print(x)
print("y")
print(y)

print("z1")
print(z1)
print("z2")
print(z2)     

x
tensor([[-1.6110e-06,  3.0638e-41,  3.7835e-44],
        [ 0.0000e+00,         nan,  4.0000e+00]])
y
tensor([[0.5493, 0.3455, 0.1613],
        [0.8927, 0.0200, 0.7378]])
z1
tensor([[0.5493, 0.3455, 0.1613],
        [0.8927,    nan, 4.7378]])
z2
tensor([[0.5493, 0.3455, 0.1613],
        [0.8927,    nan, 4.7378]])


3D data

In [6]:
# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [7]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [8]:
# Index into V and get a scalar (0 dimensional tensor)
print(V[0])
# Get a Python number from it
print(V[0].item())

tensor(1.)
1.0


"torch_cat" concatenates along the first axis (concatenates rows)

In [9]:
x = torch.randn(2, 5)
y = torch.randn(3, 5)
z = torch.cat([x, y])

print("x")
print(x)
print("y")
print(y)

print("z1")
print(z1)

x
tensor([[-0.4835,  0.5104, -0.2023, -0.2028, -0.1552],
        [ 0.0647, -1.3183, -2.1053,  1.1989, -0.4622]])
y
tensor([[ 1.2232,  0.5328,  2.0232,  0.6414,  1.5345],
        [-1.7128, -1.6619,  0.1352,  0.8093,  1.1941],
        [ 0.5861, -0.3169,  0.3659, -0.7955,  0.9197]])
z1
tensor([[0.5493, 0.3455, 0.1613],
        [0.8927,    nan, 4.7378]])


Matrix Operations

In [10]:
matrix1 = torch.randn((2,3))

print(matrix1)
print(matrix1.shape)

matrix2 = torch.randn((2,3))

print(matrix2)
print(matrix2.shape)

tensor([[2.2572e-04, 1.2846e+00, 8.3296e-01],
        [4.9660e-01, 1.4748e-01, 1.8599e-01]])
torch.Size([2, 3])
tensor([[ 1.0483, -0.2579,  0.9666],
        [ 0.3671, -0.3272, -0.0592]])
torch.Size([2, 3])


scaler operations of matrix

In [11]:
matrix1+2. #same format for '-','*','/'

tensor([[2.0002, 3.2846, 2.8330],
        [2.4966, 2.1475, 2.1860]])

In [12]:
matrix1-2

tensor([[-1.9998, -0.7154, -1.1670],
        [-1.5034, -1.8525, -1.8140]])

In [13]:
torch.abs(matrix1-2)

tensor([[1.9998, 0.7154, 1.1670],
        [1.5034, 1.8525, 1.8140]])

ceil of matrix

In [14]:
torch.ceil(matrix1)

tensor([[1., 2., 1.],
        [1., 1., 1.]])

In [15]:
matrix1 = torch.tensor([[1., 2], 
                   [2, 3], 
                   [3, 4]])
matrix1

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])

In [16]:
matrix2= torch.tensor([[4., 5], 
                   [5, 6], 
                   [6, 7]])
matrix2

tensor([[4., 5.],
        [5., 6.],
        [6., 7.]])

In [17]:
matrix1+matrix2

tensor([[ 5.,  7.],
        [ 7.,  9.],
        [ 9., 11.]])

In [18]:
matrix1/matrix2

tensor([[0.2500, 0.4000],
        [0.4000, 0.5000],
        [0.5000, 0.5714]])

einsum

In [19]:
matrix  = torch.arange(6).reshape(2,3)
matrix

tensor([[0, 1, 2],
        [3, 4, 5]])

sum of matrix

In [20]:
torch.einsum('ij->',matrix)

tensor(15)

column sum

In [21]:
torch.einsum('ij->j',matrix)

tensor([3, 5, 7])

row sum

In [22]:
torch.einsum('ij->i',matrix)

tensor([ 3, 12])

matrix vector multiplication

In [23]:
vector = torch.arange(2)
print(vector)
multi = torch.einsum('ik,i->k', [matrix, vector])
print(multi)

tensor([0, 1])
tensor([3, 4, 5])


Hadamard product

In [24]:
m1 = torch.arange(12).reshape(3,4)
m2 = torch.arange(12).reshape(3,4)

print("m1")
print(m1)
print("m2")
print(m2)

multi = torch.einsum('ij,ij->ij', [m1,m2])

print(multi)

m1
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
m2
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]])


batch multiplication

In [25]:
m1 = torch.randn(size=[7,5,3])
m2 = torch.randn(size=[7,3,2])
mat_multi = torch.einsum('bij,bjk->bik', m1, m2)
print(mat_multi.shape)

torch.Size([7, 5, 2])
