Pytorch:    
PyTorch is an optimized tensor library primarily used for Deep Learning applications using GPUs and CPUs. It is an open-source machine learning library for Python, mainly developed by the Facebook AI Research team.

In [146]:
import torch

In [147]:
# Number
t1 = torch.tensor(9.)
t1

tensor(9.)

In [148]:
# vector
t2 = torch.tensor([1,2,3,4,5])
t2

tensor([1, 2, 3, 4, 5])

Matrix

In [149]:
t3 = torch.tensor([[2., 6], 
                   [8, 9], 
                   [9, 4]])

t3

tensor([[2., 6.],
        [8., 9.],
        [9., 4.]])

In [150]:
x = torch.Tensor(2, 3)  # An un-initialized Tensor object. x holds garbage data.
y = torch.rand(2, 3)    # Initialize with random values

z1 = x + y
z2 = torch.add(x, y)            

print("x")
print(x)
print("y")
print(y)

print("z1")
print(z1)
print("z2")
print(z2)     

x
tensor([[-1.7933e-32,  3.0935e-41,  8.0000e+00],
        [ 9.0000e+00,  9.0000e+00,  4.0000e+00]])
y
tensor([[0.4671, 0.4287, 0.0630],
        [0.9877, 0.9366, 0.7358]])
z1
tensor([[0.4671, 0.4287, 8.0630],
        [9.9877, 9.9366, 4.7358]])
z2
tensor([[0.4671, 0.4287, 8.0630],
        [9.9877, 9.9366, 4.7358]])


3D data

In [151]:
# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [152]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [153]:
# Index into V and get a scalar (0 dimensional tensor)
print(V[0])
# Get a Python number from it
print(V[0].item())

tensor(1.)
1.0


"torch_cat" concatenates along the first axis (concatenates rows)

In [154]:
x = torch.randn(2, 5)
y = torch.randn(3, 5)
z = torch.cat([x, y])

print("x")
print(x)
print("y")
print(y)

print("z1")
print(z1)

x
tensor([[ 1.7810, -1.0374,  0.7953, -1.4078, -0.9821],
        [-1.5350, -0.6607,  0.4141,  0.8601,  0.9898]])
y
tensor([[-0.1341, -0.2476, -1.8864,  0.5566,  0.4314],
        [ 0.4492,  0.6467, -1.2427,  0.1160,  1.7142],
        [ 0.7885, -1.3732, -0.5717, -0.1281,  0.4939]])
z1
tensor([[0.4671, 0.4287, 8.0630],
        [9.9877, 9.9366, 4.7358]])


Matrix Operations

In [155]:
matrix1 = torch.randn((2,3))

print(matrix1)
print(matrix1.shape)

matrix2 = torch.randn((2,3))

print(matrix2)
print(matrix2.shape)

tensor([[ 1.0300,  0.2570, -0.6140],
        [-1.8296, -0.7804,  0.6980]])
torch.Size([2, 3])
tensor([[-2.1162,  0.1566, -0.2159],
        [ 0.0035, -0.4238,  0.6753]])
torch.Size([2, 3])


scaler operations of matrix

In [156]:
matrix1+2. #same format for '-','*','/'

tensor([[3.0300, 2.2570, 1.3860],
        [0.1704, 1.2196, 2.6980]])

In [157]:
matrix1-2

tensor([[-0.9700, -1.7430, -2.6140],
        [-3.8296, -2.7804, -1.3020]])

In [158]:
torch.abs(matrix1-2)

tensor([[0.9700, 1.7430, 2.6140],
        [3.8296, 2.7804, 1.3020]])

ceil of matrix

In [159]:
torch.ceil(matrix1)

tensor([[ 2.,  1., -0.],
        [-1., -0.,  1.]])

In [160]:
matrix1 = torch.tensor([[1., 2], 
                   [2, 3], 
                   [3, 4]])
matrix1

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])

In [161]:
matrix2= torch.tensor([[4., 5], 
                   [5, 6], 
                   [6, 7]])
matrix2

tensor([[4., 5.],
        [5., 6.],
        [6., 7.]])

In [162]:
matrix1+matrix2

tensor([[ 5.,  7.],
        [ 7.,  9.],
        [ 9., 11.]])

In [163]:
matrix1/matrix2

tensor([[0.2500, 0.4000],
        [0.4000, 0.5000],
        [0.5000, 0.5714]])

einsum

In [164]:
matrix  = torch.arange(6).reshape(2,3)
matrix

tensor([[0, 1, 2],
        [3, 4, 5]])

sum of matrix

In [165]:
torch.einsum('ij->',matrix)

tensor(15)

column sum

In [166]:
torch.einsum('ij->j',matrix)

tensor([3, 5, 7])

row sum

In [167]:
torch.einsum('ij->i',matrix)

tensor([ 3, 12])

matrix vector multiplication

In [168]:
vector = torch.arange(2)
print(vector)
multi = torch.einsum('ik,i->k', [matrix, vector])
print(multi)

tensor([0, 1])
tensor([3, 4, 5])


Hadamard product

In [169]:
m1 = torch.arange(12).reshape(3,4)
m2 = torch.arange(12).reshape(3,4)

print("m1")
print(m1)
print("m2")
print(m2)

multi = torch.einsum('ij,ij->ij', [m1,m2])

print(multi)

m1
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
m2
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]])


batch multiplication

In [170]:
m1 = torch.randn(size=[7,5,3])
m2 = torch.randn(size=[7,3,2])
mat_multi = torch.einsum('bij,bjk->bik', m1, m2)
print(mat_multi.shape)

torch.Size([7, 5, 2])


In [171]:
x = torch.Tensor(2, 3)  # un-initialized Tensor object. x holds garbage data.
y = torch.rand(2, 3)    # Initialize with random values

In [172]:
add_xy = torch.add(x, y)            
print(add_xy)    

tensor([[0.2671, 0.3674, 0.9000],
        [0.5947,    nan, 0.2365]])


numpy to tensor

In [173]:
import numpy as np

# Conversion
a = np.array([1, 2, 3])
vect = torch.from_numpy(a)         # Convert a numpy array to a Tensor
print(vect)

tensor([1, 2, 3])


Randome Tensor

In [174]:
a = torch.rand(2, 3)            # Initialize with random number (uniform distribution)
print(a)
b = torch.randn(2, 3)           # With normal distribution (SD=1, mean=0)
print(b)
c = torch.randperm(6)  
print(c)

tensor([[0.6034, 0.9324, 0.7711],
        [0.7839, 0.4408, 0.2015]])
tensor([[ 1.7369,  0.1768,  0.6847],
        [ 0.2760,  0.3859, -1.2818]])
tensor([3, 5, 1, 0, 4, 2])


byte tensor

In [175]:
c = torch.ByteTensor([0, 1, 1, 0])
print(c)

tensor([0, 1, 1, 0], dtype=torch.uint8)


matrix 

In [176]:
v = torch.arange(9)
v = v.view(3, 3)
print(v)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


concatenate stack

In [177]:
r = torch.stack((v, v))
print(r)

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])


split tensor

In [178]:
r = torch.chunk(v, 3)
print(r)

(tensor([[0, 1, 2]]), tensor([[3, 4, 5]]), tensor([[6, 7, 8]]))


In [179]:
r = torch.split(v, 2)
print(r)

(tensor([[0, 1, 2],
        [3, 4, 5]]), tensor([[6, 7, 8]]))


comparision operations

In [180]:
print(v)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [181]:
r = torch.eq(v, v) # element wise comparision
print(r)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [182]:
r = torch.max(v, 1) # max element with corresponding index
print(r)

torch.return_types.max(
values=tensor([2, 5, 8]),
indices=tensor([2, 2, 2]))


kth top and top k elemnts with corresponding index

In [183]:
r = torch.kthvalue(v, 2)
print(r)

torch.return_types.kthvalue(
values=tensor([1, 4, 7]),
indices=tensor([1, 1, 1]))


In [184]:
r = torch.topk(v, 1) # top k elements
print(r)

torch.return_types.topk(
values=tensor([[2],
        [5],
        [8]]),
indices=tensor([[2],
        [2],
        [2]]))


cross product

In [185]:
mat1 = torch.rand(3, 5)
mat2 = torch.rand(3, 5)
vect = torch.rand(3)

r = torch.cross(mat1, mat2)
print(r)

tensor([[-0.3015, -0.2597,  0.2749, -0.2654,  0.3982],
        [ 0.1775, -0.2725, -0.7474, -0.3187, -0.2731],
        [ 0.1304,  0.2031,  0.2509,  0.3037,  0.1436]])


diagonal matrix

In [186]:
r = torch.diag(vect)
print(r)

tensor([[0.2220, 0.0000, 0.0000],
        [0.0000, 0.0566, 0.0000],
        [0.0000, 0.0000, 0.5944]])


histogram

In [187]:
torch.histc(torch.FloatTensor([1, 2, 1]), bins=4, min=0, max=3)


tensor([0., 2., 1., 0.])

Pytorch Deep Learning Model with IRIS Dataset

multi-class classification problem based on Iris data set.    
he model will be developed classifies the samples based on four features:     
sepal length (cm).     
sepal width (cm).     
petal length (cm).    
petal width (cm).    

Class labels:     
Iris-setosa.     
Iris-versicolour.     
Iris-virginica.      

In [188]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd

dounloading data from sklearn.datasets

In [189]:
from sklearn import datasets
iris = datasets.load_iris()
X = (iris.data)
y = iris.target

In [190]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


label encoding of target column

In [191]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

split data to train and test data

In [193]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=0)

In [194]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

Creating Model      
Fully Connected Layer 4 input features, 25 output features (arbitrary).    
Fully Connected Layer 25 input features, 30 output features (arbitrary).    
Output Layer 30 input features , 3 output features.    

In [195]:
class Model(nn.Module):
    def __init__(self, input_features=4, hidden_layer1=25, hidden_layer2=30, output_features=3):
        super().__init__()
        self.fc1 = nn.Linear(input_features,hidden_layer1)                  
        self.fc2 = nn.Linear(hidden_layer1, hidden_layer2)                  
        self.out = nn.Linear(hidden_layer2, output_features)      
        
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.out(x)
        return x

model

In [196]:
model = Model()
model

Model(
  (fc1): Linear(in_features=4, out_features=25, bias=True)
  (fc2): Linear(in_features=25, out_features=30, bias=True)
  (out): Linear(in_features=30, out_features=3, bias=True)
)

setting hyperparameters:    

We start with learning rate 0.01 then we can work on and see its affect on the training process.     
Also we will use Cross Entropy and Adam optimizer.  

Learning rate is one of the key hyperparameters for gradient descent. It scales the magnitude of the model's weight updates in order to minimize the model's loss

In [197]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

train model with 100 epochs.    

EPOCH:      
An epoch is one training iteration, so in one iteration all samples are iterated once. The number determines how many times the model should be trained on the sample data.

In [198]:
epochs = 100
losses = []

for i in range(epochs):
    y_pred = model.forward(X_train)
    loss = criterion(y_pred, y_train)
    losses.append(loss)
    print(f'epoch: {i:2}  loss: {loss.item():10.8f}')
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

epoch:  0  loss: 1.24783933
epoch:  1  loss: 1.06976020
epoch:  2  loss: 1.00381613
epoch:  3  loss: 0.98972631
epoch:  4  loss: 0.96550888
epoch:  5  loss: 0.91972637
epoch:  6  loss: 0.86015183
epoch:  7  loss: 0.80437952
epoch:  8  loss: 0.75213230
epoch:  9  loss: 0.70222861
epoch: 10  loss: 0.65631020
epoch: 11  loss: 0.61491317
epoch: 12  loss: 0.57609779
epoch: 13  loss: 0.53929532
epoch: 14  loss: 0.50615466
epoch: 15  loss: 0.47874048
epoch: 16  loss: 0.45716766
epoch: 17  loss: 0.43976492
epoch: 18  loss: 0.42401999
epoch: 19  loss: 0.40831926
epoch: 20  loss: 0.39297202
epoch: 21  loss: 0.37905926
epoch: 22  loss: 0.36655760
epoch: 23  loss: 0.35344413
epoch: 24  loss: 0.33935514
epoch: 25  loss: 0.32598341
epoch: 26  loss: 0.31244263
epoch: 27  loss: 0.29733828
epoch: 28  loss: 0.28260127
epoch: 29  loss: 0.26834217
epoch: 30  loss: 0.25262052
epoch: 31  loss: 0.23762499
epoch: 32  loss: 0.22305883
epoch: 33  loss: 0.20819761
epoch: 34  loss: 0.19502625
epoch: 35  loss: 0.1

predict for test dataset

In [199]:
preds = []
with torch.no_grad():
    for val in X_test:
        y_hat = model.forward(val)
        preds.append(y_hat.argmax().item())

accuracy of model

In [200]:
data = pd.DataFrame({'Y': y_test, 'YHat': preds})
data['Correct'] = [1 if corr == pred else 0 for corr, pred in zip(data['Y'], data['YHat'])]
data['Correct'].sum() / len(data)

1.0