Tensorflow:   
TensorFlow is a framework created by Google for creating Deep Learning models. Deep Learning is a category of machine learning models (=algorithms) that use multi-layer neural networks. TensorFlow is an open-source end-to-end platform for creating Machine Learning applications

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


Tensors are characterized by their rank

Scalars - Rank 0 Tensor.   
Vector 1D array - Rank 1 Tensor.     
Matrices 2D array  - Rank 2 Tensor.     
3D array - Rank 3 Tensor




A scalar consists of a single value, it can be real or complex

In [ ]:
array_scalar = tf.constant(1)
array_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

result is tf.Tensor. scalar is rank 0 tensor.
shape is empty. datatype is int32

In [ ]:
array_scalar.numpy()

1

1D tensor is vector.

Shape has only one parameter

In [ ]:
vector_1D = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
vector_1D

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype=int32)>

In [ ]:
mat_2D = tf.constant([[-1,-2,-3,-4],
                      [5,6,7,8],
                      [9,0,1,2]]) 
mat_2D

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [ 9,  0,  1,  2]], dtype=int32)>

In [ ]:
mat_2D = tf.constant([-1,-2,-3,-4,5,6,7,8,9,0,1,2], shape = (3,4)) 
mat_2D

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [ 9,  0,  1,  2]], dtype=int32)>

creating sequence of numbers

In [ ]:
seq_nums = tf.range(start = 11,limit = 20, delta = 1)  # give start and end number the delta is the interval
seq_nums.numpy()

array([11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int32)

In [ ]:
seq_nums = tf.range(start = 15, limit = 20, delta = 0.5).numpy()
seq_nums

array([15. , 15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5],
      dtype=float32)

Slicing

This is same as numpy slicing.

In [ ]:
arr_nums = tf.range(start = 1, limit = 20)
arr_nums

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int32)>

In [ ]:
arr_nums[13:19].numpy() 


array([14, 15, 16, 17, 18, 19], dtype=int32)

In [ ]:
matrix_2D = tf.constant(tf.range(10, dtype = tf.float32), shape = (2,5))
matrix_2D

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]], dtype=float32)>

In [ ]:
matrix_2D[1:3, 2:4]

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[7., 8.]], dtype=float32)>

Transpose of matrix

In [ ]:
matrix_2D

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]], dtype=float32)>

In [ ]:
tf.transpose(matrix_2D)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 5.],
       [1., 6.],
       [2., 7.],
       [3., 8.],
       [4., 9.]], dtype=float32)>

Identity matrix

In [ ]:
tf.linalg.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

Diagonal matrix

In [ ]:
tf.linalg.diag([1,2,3,4])

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]], dtype=int32)>

In [ ]:
tf.linalg.tensor_diag(tf.constant([1,2,3,4.]))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]], dtype=float32)>

matrix of all zeros

In [ ]:
zero_matrix = tf.zeros(shape = (2,2), dtype = tf.float32) #matrix of size 2x2
zero_matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

matrix of all ones

In [ ]:
one_matrix = tf.ones(shape = (2,2), dtype = tf.int32) #matrix of size 2x2
one_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

Random uniqform matrix

In [ ]:
rand_mat = tf.random.uniform(shape = (2,2), minval = 0, maxval = 4, seed= 32)
rand_mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.67096615, 1.7603464 ],
       [1.9285107 , 3.4704132 ]], dtype=float32)>

random matrix of integers

In [ ]:
int_matrix = tf.random.uniform(shape = (4,4), minval= 1, maxval = 20, dtype = tf.int32, seed = 1234)
int_matrix

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 4, 15,  7, 18],
       [15, 16,  2, 17],
       [17,  7, 12, 13],
       [ 2, 16, 13,  2]], dtype=int32)>

sparse matrix:   
first argument is set of indices and second argument is the values of those indices. 

In [ ]:
sparse_matrix = tf.sparse.SparseTensor([[0,1],[1,3],[3,2]], [-5, -10, 7], dense_shape= (5,5))
sparse_matrix

In [ ]:
tf.sparse.to_dense(sparse_matrix) # to print sparse matrix 


<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  0,  -5,   0,   0,   0],
       [  0,   0,   0, -10,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   7,   0,   0],
       [  0,   0,   0,   0,   0]], dtype=int32)>

Matrix Multiplication

To multiply two vectors, two matrices or a matrix and a vector in a linear algebra using "limalg.matmul"

In [ ]:
vector_1 = tf.constant([1, 2, 3], shape = (3,1))
vector_1

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

Inner Product

In [ ]:
vector_2 = tf.constant([2, 3, 4], shape = (3,1))
result_inner = tf.matmul(a = vector_1, b = vector_2, transpose_a=True)
result_inner.numpy()

array([[20]], dtype=int32)

Outer Product

In [ ]:
result_outer = tf.matmul(a = vector_1, b = vector_2, transpose_b = True) # Outer product
result_outer

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]], dtype=int32)>

Matrix multiplication with vector

In [ ]:
mat = tf.constant([1,2,3,4,5,6],shape = (2,3), dtype = tf.int32)
mat

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tf.matmul(a = mat, b = vector_1).numpy()

array([[14],
       [32]], dtype=int32)

Multiplying two matrices

In [ ]:
tf.linalg.matmul(a = mat, b = mat, transpose_a=True).numpy() 

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)

Operations on matrices

In [ ]:
mat

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

Trace of matrix

In [ ]:
tf.linalg.trace(mat).numpy()

6

Rank of Matrix

In [ ]:
matrix = tf.constant([[2,6,4],
                      [6,8,3],
                   [5,1,9.]])

In [ ]:
rank = tf.linalg.matrix_rank(matrix)
rank.numpy()

3

Determinant

In [ ]:
tf.linalg.det(matrix).numpy()

-231.99998

Matrix Inverse

In [ ]:
mat_inv = tf.linalg.inv(matrix)
print(mat_inv)

tf.Tensor(
[[-0.2974138   0.21551722  0.06034485]
 [ 0.16810344  0.0086207  -0.07758622]
 [ 0.14655171 -0.12068965  0.08620689]], shape=(3, 3), dtype=float32)


extract diagonals of a matrix

In [ ]:
tf.linalg.diag_part(matrix).numpy()

array([2., 8., 9.], dtype=float32)

SVD

In [ ]:

s,u,v = tf.linalg.svd(matrix)
print("S:")
print(s)
print()
print("U:")
print(u)
print()
print("V:")
print(v)

S:
tf.Tensor([14.840091   6.8203974  2.2921445], shape=(3,), dtype=float32)

U:
tf.Tensor(
[[ 0.4734077  -0.24942522 -0.8447913 ]
 [ 0.6523388  -0.545183    0.5265261 ]
 [ 0.5918947   0.80035156  0.09538408]], shape=(3, 3), dtype=float32)

V:
tf.Tensor(
[[ 0.5269728   0.03398758  0.84920233]
 [ 0.5829514  -0.7415499  -0.33207157]
 [ 0.6184396   0.6700364  -0.4105896 ]], shape=(3, 3), dtype=float32)


Eigen values and eigen vectors

In [ ]:
values, vectors = tf.linalg.eigh(matrix)
print("Eigenvalues:")
print(values.numpy())
print()
print("Eigenvectors:")
print(vectors.numpy())

Eigenvalues:
[-2.956471   7.5711837 14.385289 ]

Eigenvectors:
[[-0.84384084  0.0734776  -0.5315391 ]
 [ 0.4332049   0.67783624 -0.59403   ]
 [ 0.31664857 -0.7315319  -0.60381675]]


Solve Linear equation

Ax=b

In [ ]:
A = tf.constant([[1,1,1],
                 [1,5,5],
                 [1,5,13]], dtype = tf.float32)
b = tf.constant([3,11,20], shape = (3,1), dtype = tf.float32)
tf.linalg.solve(A,b)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[1.   ],
       [0.875],
       [1.125]], dtype=float32)>

einsum using tensorflow

Matrix multiplication

In [ ]:
matrix1 = tf.random.normal(shape=[2, 3])
matrix1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.29369   ,  0.24478634, -0.04164693],
       [-1.440479  , -0.9627694 ,  0.63662875]], dtype=float32)>

In [ ]:
matrix2 = tf.random.normal(shape=[3, 5])
matrix2

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[ 0.64735574, -0.43018475,  0.54094315,  0.5672857 ,  2.2401955 ],
       [ 1.9242879 , -0.48644465,  0.85383445,  0.8598504 , -0.37961298],
       [ 0.9786258 ,  0.27815568, -0.01706187, -0.17818096, -0.43721738]],
      dtype=float32)>

In [ ]:
mat_multi = tf.einsum('ij,jk->ik', matrix1, matrix2)
mat_multi

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[ 0.2401607 , -0.00431838,  0.05084799,  0.05129418, -0.7326383 ],
       [-2.1621265 ,  1.2650881 , -1.612125  , -1.758436  , -3.13982   ]],
      dtype=float32)>

Dot product

In [ ]:
vector1=tf.random.normal(shape=[5])
vector1

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-0.25702372, -0.29355085,  0.89689755,  1.9278771 ,  0.43577978],
      dtype=float32)>

In [ ]:
vector2 = tf.random.normal(shape=[5])
vector2

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-0.7375148 ,  0.14806905,  1.4027451 , -1.6036427 , -0.39453766],
      dtype=float32)>

In [ ]:
dot_product = tf.einsum('i,i->', vector1, vector2)  # output = sum_i u[i]*v[i]
dot_product.numpy()

-1.8593459

Outer Product

In [ ]:
outer_product = tf.einsum('i,j->ij', vector1, vector2)
print(outer_product.shape)
print(outer_product)

(5, 5)
tf.Tensor(
[[ 0.1895588  -0.03805726 -0.36053878  0.41217422  0.10140554]
 [ 0.21649809 -0.0434658  -0.41177702  0.4707507   0.11581686]
 [-0.66147524  0.13280277  1.2581186  -1.4383032  -0.35385987]
 [-1.4218378   0.28545892  2.7043202  -3.091626   -0.7606201 ]
 [-0.32139403  0.0645255   0.61128795 -0.6988351  -0.17193154]], shape=(5, 5), dtype=float32)


In [ ]:
mat = tf.reshape(tf.range(9), [3,3])
print(mat.numpy())
diag = tf.einsum('ii->i', mat)
print(diag.numpy())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]


Trace

In [ ]:
trace = tf.einsum('ii', mat)
trace.numpy()

12

Transpose

In [ ]:
mat = tf.random.normal(shape=[5,3])
mat_transpose = tf.einsum('ij->ji', mat)
print(mat_transpose.shape)

(3, 5)


Batch Matrix Multiplication

In [ ]:
m1 = tf.random.normal(shape=[7,5,3])
m2 = tf.random.normal(shape=[7,3,2])
mat_multi = tf.einsum('bij,bjk->bik', m1, m2)
mat_multi.shape

TensorShape([7, 5, 2])

for numpy style broadcasting batch matrix multiplication

In [ ]:
m1 = tf.random.normal(shape=[11,7,5,3])
m2 = tf.random.normal(shape=[11,7,3,2])
mat_multi = tf.einsum('...ij,...jk->...ik', m1, m2)
mat_multi.shape

TensorShape([11, 7, 5, 2])

Row Sum

In [ ]:
mat = tf.random.normal(shape=[3,2])
mat_sum= tf.einsum('ij->i', mat)
print(mat_sum.shape)
print(mat_sum.numpy())

(3,)
[2.4876766  0.22848257 0.9574413 ]


Column Sum

In [ ]:
mat = tf.random.normal(shape=[3,2])
mat_sum= tf.einsum('ij->j', mat)
print(mat_sum.shape)
print(mat_sum.numpy())

(2,)
[0.63296366 0.56625164]


Tensor Contraction

In [ ]:
m1 = tf.random.normal(shape=[11,7,5,3])
m2 = tf.random.normal(shape=[11,7,3,2])
mat_multi = tf.einsum('...ij,...jk->...ik', m1, m2)

Ragged tensor:  
Data comes in many shapes, Ragged tensor is the tensorflow  makes it easy to store and process data with non-uniform shapes.

Like varibale lenght features: exmaple - set of actors in a movie dataset. 
batches of variable-length sequential inputs: example - sequences or video clips. 
Hierarchical inputs: example - text documents that are divided to sections, paras, sentences and words. 


In [ ]:
digits = tf.ragged.constant([[3, 1, 4, 1], [], [5, 9, 2], [6], []])
words = tf.ragged.constant([["So", "long"], ["thanks", "for", "all", "the", "fish"]])
print(tf.add(digits, 3))
print(tf.concat([digits, [[5, 3]]], axis=0))
print(tf.tile(digits, [1, 2]))
print(tf.strings.substr(words, 0, 2))
print(tf.map_fn(tf.math.square, digits))

<tf.RaggedTensor [[6, 4, 7, 4], [], [8, 12, 5], [9], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], [], [5, 3]]>
<tf.RaggedTensor [[3, 1, 4, 1, 3, 1, 4, 1], [], [5, 9, 2, 5, 9, 2], [6, 6], []]>
<tf.RaggedTensor [[b'So', b'lo'], [b'th', b'fo', b'al', b'th', b'fi']]>
<tf.RaggedTensor [[9, 1, 16, 1], [], [25, 81, 4], [36], []]>


expand dimensions

In [ ]:
image = tf.zeros([10,10,3])
tf.expand_dims(image, axis=0).shape.as_list()

[1, 10, 10, 3]

adding at axis 1

In [ ]:
tf.expand_dims(image, axis=1).shape.as_list()

[10, 1, 10, 3]

Shape and reshape

In [ ]:
import numpy as np

x = tf.constant(np.zeros([2, 2, 3, 12]))
shape_x = tf.shape(x, name="my_shape")
print("Shape of x: %s" % shape_x)
#rank
rank_x = tf.rank(x)
print("Rank of x: %s" % rank_x)

size_x = tf.size(x)
print("Size of x: %s" % size_x)

Shape of x: tf.Tensor([ 2  2  3 12], shape=(4,), dtype=int32)
Rank of x: tf.Tensor(4, shape=(), dtype=int32)
Size of x: tf.Tensor(144, shape=(), dtype=int32)


In [ ]:
x = tf.constant(np.arange(1, 13))
print("x = %s\n" % x)

x_reshape = tf.reshape(x, [2, -1])
print("x_2_6 = %s\n" % x_reshape)

x = tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int64)

x_2_6 = tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int64)



Squeezing Tensors

In [ ]:
x = tf.constant(np.reshape(np.arange(1, 5), [2, 1, 2, 1]))
print("Shape of x = %s" % x.shape)
print(x)

# Now squeeze out all the dimensions of length 1
x_squeezed = tf.squeeze(x)
print("\nShape of x_squeezed = %s" % x_squeezed.shape)
print(x_squeezed)

Shape of x = (2, 1, 2, 1)
tf.Tensor(
[[[[1]
   [2]]]


 [[[3]
   [4]]]], shape=(2, 1, 2, 1), dtype=int64)

Shape of x_squeezed = (2, 2)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


Tensor Data types

Integer types: tf.int32, tf.int64.  
Float types: tf.float32, tf.float64.  
Boolean type: tf.bool.  
Complex type: tf.complex64, tf.complex128

In [ ]:
int32_tensor = tf.constant([1, 1], dtype=tf.int32)
print(int32_tensor)
float32_tensor = tf.constant([2, 2], dtype=tf.float32)
print(float32_tensor)

tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([2. 2.], shape=(2,), dtype=float32)


Comparision Operations

In [ ]:
a = tf.constant([1.0, 1.0])
b = tf.constant([2.0, 2.0])
c = tf.constant([1.0, 2.0])
d = 3.0

print ("Inputs:\na: %s\nb: %s\nc: %s\nd: %s\n" % (a, b, c, d))
# Less-than op. Tests if the first argument is less than the second argument
# component wise.
a_less_than_b = a < b
b_greater_than_c = b > c

# Simple broadcasting in action
a_less_than_d = a < d

# More complex broadcasting
a2 = tf.constant([[1,2],[2,3]])
b2 = tf.constant([1,3])
c2 = tf.equal(a2, b2)

# Note that there is no inline form for tf.equals. If you do b == c, you will
# not get what you think you might.
b_equal_to_c = tf.equal(b, c)

outputs = (a_less_than_b, b_greater_than_c, a_less_than_d,  b_equal_to_c)

print("Outputs:\na < b: %s\nb > c: %s\na < d: %s\nb == c: %s\n" % (outputs))


print("Complex Broadcasting")
print("%s == %s => %s" % (a2.numpy(), b2.numpy(), c2.numpy()))

Inputs:
a: tf.Tensor([1. 1.], shape=(2,), dtype=float32)
b: tf.Tensor([2. 2.], shape=(2,), dtype=float32)
c: tf.Tensor([1. 2.], shape=(2,), dtype=float32)
d: 3.0

Outputs:
a < b: tf.Tensor([ True  True], shape=(2,), dtype=bool)
b > c: tf.Tensor([ True False], shape=(2,), dtype=bool)
a < d: tf.Tensor([ True  True], shape=(2,), dtype=bool)
b == c: tf.Tensor([False  True], shape=(2,), dtype=bool)

Complex Broadcasting
[[1 2]
 [2 3]] == [1 3] => [[ True False]
 [False  True]]


Using Tensorflow on iris data 

multi-class classification problem based on Iris data set.  
he model will be developed classifies the samples based on four features:   
sepal length (cm).  
sepal width (cm).   
petal length (cm).  
petal width (cm).  

Class labels:    
Iris-setosa.   
Iris-versicolour.   
Iris-virginica.   

import libraries

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

dounloading data from sklearn.datasets

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [ ]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


label encoding of target column

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [ ]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


split the data to train and text data

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

define mode

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])
model

compile model

In [ ]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

train model with 100 epochs

EPOCH:  
An epoch is one training iteration, so in one iteration all samples are iterated once. The number determines how many times the model should be trained on the sample data.

In [ ]:
model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
3/3 [==============================] - 1s 8ms/step - loss: 1.7033 - accuracy: 0.3667
Epoch 2/100
3/3 [==============================] - 0s 7ms/step - loss: 1.5351 - accuracy: 0.3667
Epoch 3/100
3/3 [==============================] - 0s 7ms/step - loss: 1.4484 - accuracy: 0.3667
Epoch 4/100
3/3 [==============================] - 0s 7ms/step - loss: 1.3797 - accuracy: 0.3667
Epoch 5/100
3/3 [==============================] - 0s 6ms/step - loss: 1.3281 - accuracy: 0.3667
Epoch 6/100
3/3 [==============================] - 0s 5ms/step - loss: 1.2893 - accuracy: 0.3667
Epoch 7/100
3/3 [==============================] - 0s 5ms/step - loss: 1.2625 - accuracy: 0.3667
Epoch 8/100
3/3 [==============================] - 0s 5ms/step - loss: 1.2371 - accuracy: 0.3667
Epoch 9/100
3/3 [==============================] - 0s 5ms/step - loss: 1.2161 - accuracy: 0.3667
Epoch 10/100
3/3 [==============================] - 0s 6ms/step - loss: 1.1972 - accuracy: 0.3667
Epoch 11/100
3/3 [===========

Accuracy of model

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.43093711137771606
Test accuracy: 0.7333333492279053


In [ ]:
y_pred = model.predict(X_test)
y_pred

array([[0.00760287, 0.23295274, 0.75944436],
       [0.08175907, 0.47513947, 0.44310144],
       [0.9567326 , 0.03999832, 0.0032692 ],
       [0.00518291, 0.22340941, 0.77140766],
       [0.9158549 , 0.07587709, 0.00826793],
       [0.00471443, 0.21010827, 0.7851773 ],
       [0.9241582 , 0.0687373 , 0.00710454],
       [0.05494431, 0.46251136, 0.48254442],
       [0.04245368, 0.43337435, 0.524172  ],
       [0.10130168, 0.4985978 , 0.40010047],
       [0.01313186, 0.3042281 , 0.68264014],
       [0.07212914, 0.48437548, 0.44349536],
       [0.04959253, 0.4622508 , 0.4881567 ],
       [0.04328604, 0.43446988, 0.5222441 ],
       [0.04248964, 0.44438776, 0.51312256],
       [0.93139124, 0.06218218, 0.00642657],
       [0.04617047, 0.4484536 , 0.5053759 ],
       [0.04999043, 0.4518557 , 0.49815387],
       [0.8866945 , 0.10097694, 0.01232857],
       [0.94313365, 0.05222806, 0.00463831],
       [0.01365563, 0.29431862, 0.6920258 ],
       [0.04759829, 0.45383793, 0.4985638 ],
       [0.