In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.0


Tensors are characterized by their rank

Scalars - Rank 0 Tensor.   
Vector 1D array - Rank 1 Tensor.     
Matrices 2D array  - Rank 2 Tensor.     
3D array - Rank 3 Tensor




A scalar consists of a single value, it can be real or complex

In [2]:
array_scalar = tf.constant(1)
array_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

result is tf.Tensor. scalar is rank 0 tensor.
shape is empty. datatype is int32

In [3]:
array_scalar.numpy()

1

1D tensor is vector.

Shape has only one parameter

In [4]:
vector_1D = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
vector_1D

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype=int32)>

In [5]:
mat_2D = tf.constant([[-1,-2,-3,-4],
                      [5,6,7,8],
                      [9,0,1,2]]) 
mat_2D

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [ 9,  0,  1,  2]], dtype=int32)>

In [6]:
mat_2D = tf.constant([-1,-2,-3,-4,5,6,7,8,9,0,1,2], shape = (3,4)) 
mat_2D

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [ 9,  0,  1,  2]], dtype=int32)>

creating sequence of numbers

In [7]:
seq_nums = tf.range(start = 11,limit = 20, delta = 1)  # give start and end number the delta is the interval
seq_nums.numpy()

array([11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int32)

In [8]:
seq_nums = tf.range(start = 15, limit = 20, delta = 0.5).numpy()
seq_nums

array([15. , 15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5],
      dtype=float32)

Slicing

This is same as numpy slicing.

In [9]:
arr_nums = tf.range(start = 1, limit = 20)
arr_nums

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int32)>

In [10]:
arr_nums[13:19].numpy() 


array([14, 15, 16, 17, 18, 19], dtype=int32)

In [11]:
matrix_2D = tf.constant(tf.range(10, dtype = tf.float32), shape = (2,5))
matrix_2D

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]], dtype=float32)>

In [12]:
matrix_2D[1:3, 2:4]

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[7., 8.]], dtype=float32)>

Transpose of matrix

In [13]:
matrix_2D

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]], dtype=float32)>

In [14]:
tf.transpose(matrix_2D)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 5.],
       [1., 6.],
       [2., 7.],
       [3., 8.],
       [4., 9.]], dtype=float32)>

Identity matrix

In [15]:
tf.linalg.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

Diagonal matrix

In [16]:
tf.linalg.diag([1,2,3,4])

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]], dtype=int32)>

In [17]:
tf.linalg.tensor_diag(tf.constant([1,2,3,4.]))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]], dtype=float32)>

matrix of all zeros

In [18]:
zero_matrix = tf.zeros(shape = (2,2), dtype = tf.float32) #matrix of size 2x2
zero_matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

matrix of all ones

In [19]:
one_matrix = tf.ones(shape = (2,2), dtype = tf.int32) #matrix of size 2x2
one_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

Random uniqform matrix

In [20]:
rand_mat = tf.random.uniform(shape = (2,2), minval = 0, maxval = 4, seed= 32)
rand_mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.8862844 , 0.21059465],
       [1.4039903 , 3.5476441 ]], dtype=float32)>

random matrix of integers

In [21]:
int_matrix = tf.random.uniform(shape = (4,4), minval= 1, maxval = 20, dtype = tf.int32, seed = 1234)
int_matrix

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[16, 14,  5, 14],
       [12,  7,  3, 11],
       [14,  8,  1,  3],
       [17,  7, 19,  9]], dtype=int32)>

sparse matrix:   
first argument is set of indices and second argument is the values of those indices. 

In [22]:
sparse_matrix = tf.sparse.SparseTensor([[0,1],[1,3],[3,2]], [-5, -10, 7], dense_shape= (5,5))
sparse_matrix

In [23]:
tf.sparse.to_dense(sparse_matrix) # to print sparse matrix 


<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  0,  -5,   0,   0,   0],
       [  0,   0,   0, -10,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   7,   0,   0],
       [  0,   0,   0,   0,   0]], dtype=int32)>

Matrix Multiplication

To multiply two vectors, two matrices or a matrix and a vector in a linear algebra using "limalg.matmul"

In [24]:
vector_1 = tf.constant([1, 2, 3], shape = (3,1))
vector_1

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

Inner Product

In [25]:
vector_2 = tf.constant([2, 3, 4], shape = (3,1))
result_inner = tf.matmul(a = vector_1, b = vector_2, transpose_a=True)
result_inner.numpy()

array([[20]], dtype=int32)

Outer Product

In [26]:
result_outer = tf.matmul(a = vector_1, b = vector_2, transpose_b = True) # Outer product
result_outer

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]], dtype=int32)>

Matrix multiplication with vector

In [27]:
mat = tf.constant([1,2,3,4,5,6],shape = (2,3), dtype = tf.int32)
mat

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [28]:
tf.matmul(a = mat, b = vector_1).numpy()

array([[14],
       [32]], dtype=int32)

Multiplying two matrices

In [29]:
tf.linalg.matmul(a = mat, b = mat, transpose_a=True).numpy() 

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)

Operations on matrices

In [30]:
mat

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

Trace of matrix

In [31]:
tf.linalg.trace(mat).numpy()

6

Rank of Matrix

In [32]:
matrix = tf.constant([[2,6,4],
                      [6,8,3],
                   [5,1,9.]])

In [33]:
rank = tf.linalg.matrix_rank(matrix)
rank.numpy()

3

Determinant

In [34]:
tf.linalg.det(matrix).numpy()

-231.99998

Matrix Inverse

In [35]:
mat_inv = tf.linalg.inv(matrix)
print(mat_inv)

tf.Tensor(
[[-0.2974138   0.21551722  0.06034485]
 [ 0.16810344  0.0086207  -0.07758622]
 [ 0.14655171 -0.12068965  0.08620689]], shape=(3, 3), dtype=float32)


extract diagonals of a matrix

In [36]:
tf.linalg.diag_part(matrix).numpy()

array([2., 8., 9.], dtype=float32)

SVD

In [37]:

s,u,v = tf.linalg.svd(matrix)
print("S:")
print(s)
print()
print("U:")
print(u)
print()
print("V:")
print(v)

S:
tf.Tensor([14.840091   6.8203974  2.2921445], shape=(3,), dtype=float32)

U:
tf.Tensor(
[[ 0.4734077  -0.24942522 -0.8447913 ]
 [ 0.6523388  -0.545183    0.5265261 ]
 [ 0.5918947   0.80035156  0.09538408]], shape=(3, 3), dtype=float32)

V:
tf.Tensor(
[[ 0.5269728   0.03398758  0.84920233]
 [ 0.5829514  -0.7415499  -0.33207157]
 [ 0.6184396   0.6700364  -0.4105896 ]], shape=(3, 3), dtype=float32)


Eigen values and eigen vectors

In [38]:
values, vectors = tf.linalg.eigh(matrix)
print("Eigenvalues:")
print(values.numpy())
print()
print("Eigenvectors:")
print(vectors.numpy())

Eigenvalues:
[-2.956471   7.5711837 14.385289 ]

Eigenvectors:
[[-0.84384084  0.0734776  -0.5315391 ]
 [ 0.4332049   0.67783624 -0.59403   ]
 [ 0.31664857 -0.7315319  -0.60381675]]


Solve Linear equation

Ax=b

In [39]:
A = tf.constant([[1,1,1],
                 [1,5,5],
                 [1,5,13]], dtype = tf.float32)
b = tf.constant([3,11,20], shape = (3,1), dtype = tf.float32)
tf.linalg.solve(A,b)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[1.   ],
       [0.875],
       [1.125]], dtype=float32)>

einsum using tensorflow

Matrix multiplication

In [40]:
matrix1 = tf.random.normal(shape=[2, 3])
matrix1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.0804713 ,  1.1723061 , -0.8845799 ],
       [-0.30128077,  0.4789044 ,  0.44636124]], dtype=float32)>

In [41]:
matrix2 = tf.random.normal(shape=[3, 5])
matrix2

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[-0.37421444,  1.4787824 ,  0.36400682,  0.92561626,  0.05378715],
       [ 0.15726691,  1.5305665 , -0.9653605 , -0.6713042 ,  0.10549844],
       [ 0.15593481, -1.1829135 ,  0.13334902,  0.83039224,  0.06426253]],
      dtype=float32)>

In [42]:
mat_multi = tf.einsum('ij,jk->ik', matrix1, matrix2)
mat_multi

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[-0.35789979,  4.4384556 , -0.856357  , -0.5214205 ,  0.12494659],
       [ 0.25766268, -0.24054039, -0.51246184, -0.22970602,  0.06300294]],
      dtype=float32)>

Dot product

In [43]:
vector1=tf.random.normal(shape=[5])
vector1

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-0.8791624 , -0.08268324,  0.4290936 ,  0.22356713, -1.5121402 ],
      dtype=float32)>

In [44]:
vector2 = tf.random.normal(shape=[5])
vector2

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([ 0.04587993,  2.5970995 ,  1.948742  , -1.1039081 ,  0.74829835],
      dtype=float32)>

In [45]:
dot_product = tf.einsum('i,i->', vector1, vector2)  # output = sum_i u[i]*v[i]
dot_product.numpy()

-0.79720926

Outer Product

In [46]:
outer_product = tf.einsum('i,j->ij', vector1, vector2)
print(outer_product.shape)
print(outer_product)

(5, 5)
tf.Tensor(
[[-4.0335912e-02 -2.2832723e+00 -1.7132607e+00  9.7051442e-01
  -6.5787578e-01]
 [-3.7935013e-03 -2.1473660e-01 -1.6112830e-01  9.1274694e-02
  -6.1871730e-02]
 [ 1.9686786e-02  1.1143988e+00  8.3619273e-01 -4.7367987e-01
   3.2109004e-01]
 [ 1.0257245e-02  5.8062607e-01  4.3567467e-01 -2.4679756e-01
   1.6729492e-01]
 [-6.9376893e-02 -3.9271786e+00 -2.9467711e+00  1.6692637e+00
  -1.1315320e+00]], shape=(5, 5), dtype=float32)


In [47]:
mat = tf.reshape(tf.range(9), [3,3])
print(mat.numpy())
diag = tf.einsum('ii->i', mat)
print(diag.numpy())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]


Trace

In [48]:
trace = tf.einsum('ii', mat)
trace.numpy()

12

Transpose

In [49]:
mat = tf.random.normal(shape=[5,3])
mat_transpose = tf.einsum('ij->ji', mat)
print(mat_transpose.shape)

(3, 5)


Batch Matrix Multiplication

In [50]:
m1 = tf.random.normal(shape=[7,5,3])
m2 = tf.random.normal(shape=[7,3,2])
mat_multi = tf.einsum('bij,bjk->bik', m1, m2)
mat_multi.shape

TensorShape([7, 5, 2])

for numpy style broadcasting batch matrix multiplication

In [51]:
m1 = tf.random.normal(shape=[11,7,5,3])
m2 = tf.random.normal(shape=[11,7,3,2])
mat_multi = tf.einsum('...ij,...jk->...ik', m1, m2)
mat_multi.shape

TensorShape([11, 7, 5, 2])

Row Sum

In [52]:
mat = tf.random.normal(shape=[3,2])
mat_sum= tf.einsum('ij->i', mat)
print(mat_sum.shape)
print(mat_sum.numpy())

(3,)
[1.6681523 2.0578218 0.7787191]


Column Sum

In [53]:
mat = tf.random.normal(shape=[3,2])
mat_sum= tf.einsum('ij->j', mat)
print(mat_sum.shape)
print(mat_sum.numpy())

(2,)
[2.0879273 1.0519593]


Tensor Contraction

In [54]:
m1 = tf.random.normal(shape=[11,7,5,3])
m2 = tf.random.normal(shape=[11,7,3,2])
mat_multi = tf.einsum('...ij,...jk->...ik', m1, m2)

Ragged tensor:  
Data comes in many shapes, Ragged tensor is the tensorflow  makes it easy to store and process data with non-uniform shapes.

Like varibale lenght features: exmaple - set of actors in a movie dataset. 
batches of variable-length sequential inputs: example - sequences or video clips. 
Hierarchical inputs: example - text documents that are divided to sections, paras, sentences and words. 


In [56]:
digits = tf.ragged.constant([[3, 1, 4, 1], [], [5, 9, 2], [6], []])
words = tf.ragged.constant([["So", "long"], ["thanks", "for", "all", "the", "fish"]])
print(tf.add(digits, 3))
print(tf.concat([digits, [[5, 3]]], axis=0))
print(tf.tile(digits, [1, 2]))
print(tf.strings.substr(words, 0, 2))
print(tf.map_fn(tf.math.square, digits))

<tf.RaggedTensor [[6, 4, 7, 4], [], [8, 12, 5], [9], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], [], [5, 3]]>
<tf.RaggedTensor [[3, 1, 4, 1, 3, 1, 4, 1], [], [5, 9, 2, 5, 9, 2], [6, 6], []]>
<tf.RaggedTensor [[b'So', b'lo'], [b'th', b'fo', b'al', b'th', b'fi']]>
<tf.RaggedTensor [[9, 1, 16, 1], [], [25, 81, 4], [36], []]>


expand dimensions

In [57]:
image = tf.zeros([10,10,3])
tf.expand_dims(image, axis=0).shape.as_list()

[1, 10, 10, 3]

adding at axis 1

In [58]:
tf.expand_dims(image, axis=1).shape.as_list()

[10, 1, 10, 3]

Shape and reshape

In [60]:
import numpy as np

x = tf.constant(np.zeros([2, 2, 3, 12]))
shape_x = tf.shape(x, name="my_shape")
print("Shape of x: %s" % shape_x)
#rank
rank_x = tf.rank(x)
print("Rank of x: %s" % rank_x)

size_x = tf.size(x)
print("Size of x: %s" % size_x)

Shape of x: tf.Tensor([ 2  2  3 12], shape=(4,), dtype=int32)
Rank of x: tf.Tensor(4, shape=(), dtype=int32)
Size of x: tf.Tensor(144, shape=(), dtype=int32)


In [62]:
x = tf.constant(np.arange(1, 13))
print("x = %s\n" % x)

x_reshape = tf.reshape(x, [2, -1])
print("x_2_6 = %s\n" % x_reshape)

x = tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int64)

x_2_6 = tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int64)



Squeezing Tensors

In [65]:
x = tf.constant(np.reshape(np.arange(1, 5), [2, 1, 2, 1]))
print("Shape of x = %s" % x.shape)
print(x)

# Now squeeze out all the dimensions of length 1
x_squeezed = tf.squeeze(x)
print("\nShape of x_squeezed = %s" % x_squeezed.shape)
print(x_squeezed)

Shape of x = (2, 1, 2, 1)
tf.Tensor(
[[[[1]
   [2]]]


 [[[3]
   [4]]]], shape=(2, 1, 2, 1), dtype=int64)

Shape of x_squeezed = (2, 2)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


Tensor Data types

Integer types: tf.int32, tf.int64.  
Float types: tf.float32, tf.float64.  
Boolean type: tf.bool.  
Complex type: tf.complex64, tf.complex128

In [71]:
int32_tensor = tf.constant([1, 1], dtype=tf.int32)
print(int32_tensor)
float32_tensor = tf.constant([2, 2], dtype=tf.float32)
print(float32_tensor)

tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([2. 2.], shape=(2,), dtype=float32)


Comparision Operations

In [72]:
a = tf.constant([1.0, 1.0])
b = tf.constant([2.0, 2.0])
c = tf.constant([1.0, 2.0])
d = 3.0

print ("Inputs:\na: %s\nb: %s\nc: %s\nd: %s\n" % (a, b, c, d))
# Less-than op. Tests if the first argument is less than the second argument
# component wise.
a_less_than_b = a < b
b_greater_than_c = b > c

# Simple broadcasting in action
a_less_than_d = a < d

# More complex broadcasting
a2 = tf.constant([[1,2],[2,3]])
b2 = tf.constant([1,3])
c2 = tf.equal(a2, b2)

# Note that there is no inline form for tf.equals. If you do b == c, you will
# not get what you think you might.
b_equal_to_c = tf.equal(b, c)

outputs = (a_less_than_b, b_greater_than_c, a_less_than_d,  b_equal_to_c)

print("Outputs:\na < b: %s\nb > c: %s\na < d: %s\nb == c: %s\n" % (outputs))


print("Complex Broadcasting")
print("%s == %s => %s" % (a2.numpy(), b2.numpy(), c2.numpy()))

Inputs:
a: tf.Tensor([1. 1.], shape=(2,), dtype=float32)
b: tf.Tensor([2. 2.], shape=(2,), dtype=float32)
c: tf.Tensor([1. 2.], shape=(2,), dtype=float32)
d: 3.0

Outputs:
a < b: tf.Tensor([ True  True], shape=(2,), dtype=bool)
b > c: tf.Tensor([ True False], shape=(2,), dtype=bool)
a < d: tf.Tensor([ True  True], shape=(2,), dtype=bool)
b == c: tf.Tensor([False  True], shape=(2,), dtype=bool)

Complex Broadcasting
[[1 2]
 [2 3]] == [1 3] => [[ True False]
 [False  True]]
